### ISSUE TITLE
bspwm appears to feeze, bspc calls block, clicking in windows doesn't work

### ISSUE THREAD

**Issue by alexozer** [baskerville/bspwm#853] opened 2018-09-26 17:39 UTC
It's strange, but at least a few times a day I will encounter bspwm freezing. It might freeze right after a bspc call, though I'm not entirely sure. When it happens, bspc calls appear to never terminate and clicking in windows doesn't always appear to work correctly (probably an effect of focus not being handled anymore because bspwm froze).

The last time this happened I switched to a virtual console and tried running bspc manually:

```
$ export BSPWM_SOCKET=/tmp/bspwm_0_0-socket
$ bspc quit          # freezes
```

Here's my whole configuration: https://github.com/alexozer/dotfiles/tree/master/bspwm/.config

**Comment by baskerville** [comment] 2018-09-26 18:15
This is a duplicate of #849.

**Closed by baskerville** 2018-09-26 18:15 UTC
