### ISSUE TITLE
Odd behavior when changing border_width

### ISSUE THREAD

**Issue by ZVak18** [baskerville/bspwm#1092] opened 2020-04-08 05:32 UTC
I noticed today that whenever I change the border_width beyond 2, the windows shift in a such a way that right clicking inside browser windows causes them to auto click when using right menu.

For example: Set border_width to 10, the border changes. Reload the changes with an open window to see the shift. Then when using a browser, right click to open content menu and you'll auto click the first option (usually easier if you navigate to page for it to choose the back option). 

This happens to floating and tiled windows, but only seems to affect browser windows. Right clicking inside programs works as normal (tested gimp, steam, thunar, atom).

**Comment by jallbrit** [comment] 2020-07-27 19:40
Confirmed, I can reproduce this behavior. I'm not what's causing it, though. Are you also using Firefox? It seems that the right click context menu is being created based on the cursor's offset to the corner of the window, but it doesn't take into account the border width.

**Comment by jallbrit** [comment] 2020-07-27 19:53
This issue is basically a duplicate of #1015. @ZVak18 you should consider closing this.

**Closed** 2020-08-13 15:00 UTC
