### ISSUE TITLE
Almost zero documentation

### ISSUE THREAD

**Issue by Sbatushe** [baskerville/bspwm#1228] opened 2020-11-20 00:05 UTC
There is no doumentation on how to use bspwm: the `bspwm -h` command is useless; `bspc -h` option doesn't exist.
There is no pratical way to access to bspc options needed to configure the keyboard daemon properly.

edit:
Bspwm man page can be improved with userful informations.

**Comment by turquoise-hexagon** [comment] 2020-11-20 00:09
`man bspc` and `man sxhkd` have all the informations you need

**Comment by Sbatushe** [comment] 2020-11-20 18:49
I suggest to add an actual help option using the `-h` flag both on bspwm and bspc, then is also a good practise to add code comments on sxhkd config file generated by default.

**Comment by emanuele6** [comment] 2020-11-30 15:28
> I suggest to add an actual help option using the -h flag both on bspwm and bspc

@Sbatushe `bspwm` has a `-h` option. And if you are asking for an help option for `bspc`, this issue is a duplicate of #776.

Also, in my opinion, having `bspc -h` doesn't make any sense. If `bspc` had an help feature, it should be under an "help" domain (i.e. `bspc help`) like all the other features.

**Comment by Sbatushe** [comment] 2020-11-30 19:44
I'm trying to help because i think bspwm is one of the best tiling window managers, but it lacks of documentation, so i wrote some suggestions:

the `bspwm -h` option is  far away to be an help option. it should be something like:
```
Usage:
    -h               show this help
    -v               show bspwm version and exit
    -c CONFIG_PATH   run bspwm using a custom configuration file
```
which is minimal but userful.
I'm not talking about bspc because the user downloads bspwm, and so the first thing the user will do is `bspwm -h`.

Also in the manpage there is lack of information; to see what i mean you can just compare `man bspwm` with `man i3`; i suggest to add something like this in the `man bspwm` page:
```
CONFIGURATION
The configuration of bspwm is done using bspc commands which are used to configure the window manager and keyboard shortcuts.
To properly configure your bspwm environment you need to:

        -configure bspwm file: this file contains the main configuration of the window manager;
         the default location of bspwmrc is /usr/share/doc/bspwm/examples/bspwmrc

        -configure keybinds: bspwm keybinds needs to be managed by an external daemon
         (such as sxhd); to do so you can use the default sxhd configuration file, which is 
         /usr/share/doc/bspwm/examples/sxhdrc 

You may want to copy/install bspwmrc from the default location into ~/.config/bspwm/ and sxhkdrc into ~/.config/sxhkd/.
The file bspwmrc needs to be executable since the default example is simply a shell script that in turn configures bspwm via the bspc command. Is also userful to add a .conf extension to your configuration files so enable syntax highlight.
```
Another problem is lack of comments in the default sxhdrc  which make the configuration really painful, there are no options or hints on alternative configurations in this file. As before i can refer to i3's config file as a comparison parameter.

Finally there are a lot of other things that could be added, the arch wiki can be considered a good **starting** point. 

_https://wiki.archlinux.org/index.php/Bspwm_

Probably i need to say it again, i may be direct but bspwm lacks of documentation and that's not an opinion but a fact: it's a widely known flaw and i'm trying to help to fix this because bspwm is a very good software and i want it to grow.

**Comment by emanuele6** [comment] 2020-12-01 02:21
> Also in the manpage there is lack of information; to see what i mean you can just compare `man bspwm` with `man i3`

AFAIK barely anything is documented (to not say anything at all) in the manual pages of `i3wm` (`i3(1)` and `i3-msg(1)`).

All of `i3`'s documentation is on the website.

Also we already discussed `i3` documentation vs `bspwm` documentation on reddit one year ago if you want to read it: [link](https://www.reddit.com/r/bspwm/comments/cqxrd8/distrotube_currently_trying_out_bspwm/ex2s7tz).

Also note that many people, including myself, really like `bspwm`'s manual page (especially compared to `i3wm`'s): [example](https://www.reddit.com/r/bspwm/comments/j0de53/bspc_and_bspcs_man_page_are_amazing/).

> the bspwm -h option is far away to be an help option. it should be something like:
```
Usage:
    -h               show this help
    -v               show bspwm version and exit
    -c CONFIG_PATH   run bspwm using a custom configuation file
```
which is minimal but userful.

To be honest, I don't see how that is that much better than:
```
bspwm [-h|-v|-c CONFIG_PATH]
```
`-h` and `-v` are obvious and `-c` is explained enough by the name of the argument. Your example is, at best, more confusing since you say that `" and exit"` for `-v` and not for `-h`. Note that this is also the help format that some programs from [wmutils](https://github.com/wmutils) use (e.g. `wattr`).

**Comment by Sbatushe** [comment] 2020-12-09 00:10
Surely bsp is documented, but the problem is it's badly documented!

Emanuele you know why i use bspwm? Because of arch-wiki and youtube. If i had to learn how to use this wm reading hundreds of manpage lines and bspc commands probably i were still using Xfce+i3.
Why? because even if bsp is more customizable than i3, at least with i3 i can read official documentation on the website with **examples** and **userful** helps and for me that's more important than the features (i've already shown why bsp manpage have not all the information a default noob user needs).
Bsp is very confusing: i've spent a week configuring it even with arch wiki and youtube videos. (vs just some hours for i3).

Example:
Some days ago i had a problem with android studio and other java apps, do you know where i found some help? well surely not in the manpage but on the archwiki documentation (_https://wiki.archlinux.org/index.php/Bspwm_ in the _Troubleshooting_ section). 

I hope that the problem here is not the mind behind the coding: if the devs are not making a good documentation because they think that user-friendly programs are stupid programs than that's a shame because (if that's the case) we need to make some computer science lessons for beginners.
-h and -v are obvious. This should be the reason to not specify commands? Damn i studied theese things on the first computer science year! Even if something is obvious for some/most-of the users it needs to be specified to make ALL the users understand.
i highly suggest to make some good official documentation using an user-friendly website like _http://docs.qtile.org/en/latest/_ or _https://www.debian.org/doc/_  (the well documented manpage and -h options are the bare-decency minimum for an user driven program).

If you don't want to improve documentation that's fine for me, i don't care because this piece of software is not mine and i know (because of external documentation) how to use it, but i just think that's a shame for bsp.

This situation is a very rare case of a very important problem with an easy-dumb fix: how much it will cost? 1 day or 2?

**Comment by emanuele6** [comment] 2020-12-09 10:09
> -h and -v are obvious. This should be the reason to not specify commands?

You are only complaining about the style of the help message here. These options are described in the manual page:
``` 
OPTIONS
       -h
           Print the synopsis and exit.

       -v
           Print the version and exit.

       -c CONFIG_PATH
           Use the given configuration file.
```

Every single feature in `bspwm` is documented on the manual page: example: "how the change the state of a window"
```
DOMAINS
   Node
       General Syntax
           node [NODE_SEL] COMMANDS

           If NODE_SEL is omitted, focused is assumed.

       Commands
[...]
           -t, --state [~](tiled|pseudo_tiled|floating|fullscreen)
               Set the state of the selected window. If ~ is present and the
               current state matches the given state, then the argument is
               interpreted as the last state.
```
"what are the window states":
```
WINDOW STATES
       tiled
           Its size and position are determined by the window tree.

       pseudo_tiled
           A tiled window that automatically shrinks but doesn’t stretch
           beyond its floating size.

       floating
           Can be moved/resized freely. Although it doesn’t use any tiling
           space, it is still part of the window tree.

       fullscreen
           Fills its monitor rectangle and has no borders.
```
"how to select a node": ... 

----------------------

In the `i3` manual page, most things aren't documented; examples:
* reading `i3(1)`, I won't learn how to set a rule to, for example, make `firefox` windows open in the third desktop.
* reading `i3-msg(1)`, I won't learn how to make a window floating with a command.

Most things are only documented on their website, split between different pages with no global search bar to search in all the pages.  

-------

All I said about adding an help option to `bspc` is that, in my opinion, it should be under `bspc help` for consistency, not under `bspc -h`; and that, if this issue is about adding an help option to `bspc`, this issue is a duplicate of another open issue.

You keep going from "bspwm has almost zero documentation" to "man bspwm exists, but it can be improved" to "bspwm is badly documented" to "the bspwm manual page is well documented, but that is just bare-decency for **a** user driven program".

I don't understand what you are complaining about.

**Comment by Filip62** [comment] 2020-12-12 11:56
There are useful examples in this repository. They do not provide comments why they are like that, because they are just examples not documentation/manuals. Every user of Linux should know that, if they see a command they do not understand how to use they should check the manpage for it first. And surely everything is there.

If you want a tutorial, then find it on youtube or where-ever, just like you did.

Bspwm is not tied to any hotkey daemon. You can use want you want. And again there is a simple sxhkd config example in this repo and with comments for that matter, and it has a great manpage.

I started with bspwm just a few weeks ago and all I needed, were the examples in this repo and the manpages.

I agree with @emanuele6. You should rethink your documentation problem @Sbatushe.

**Comment by greyhatmiddleman** [comment] 2020-12-23 17:05
@Sbatushe why don't you fork and contribute to the cause. Just like other software where can you find the best documentation to anything these days. Wait until you get your hands on suckless software, good luck to you.

**Closed** 2020-12-29 12:49 UTC
