### ISSUE TITLE
Borders question

### ISSUE THREAD

**Issue by BillyTheMotherBoard** [baskerville/bspwm#871] opened 2018-11-05 21:16 UTC
Hello man,
first of all, thank you for bspwm, I like it and I'm experimenting with it at the moment so keep up the good work :)

I'm replicating a 2bwm setup in bspwm and my problem is getting the same borders look as the pic here:

https://camo.githubusercontent.com/00e0d86ad181547de6bcca9df944b944a523e9ca/68747470733a2f2f3078302e73742f737175352e706e67

I think it's called double borders, do you know if I can do that in bspwm? 
Thank you if you read this man,
Have a nice day!

**Comment by neeasade** [comment] 2018-11-05 21:34
You can use `chwb2` from https://github.com/wmutils/opt in `bspwm`

**Comment by jallbrit** [comment] 2020-08-10 05:00
@baskerville please close, this is another duplicate of #492

**Closed** 2020-08-10 08:01 UTC
