### ISSUE TITLE
Monocle for the leaf-area

### ISSUE THREAD

**Issue by astier** [baskerville/bspwm#983] opened 2019-07-05 00:04 UTC
I am not sure if I am using the correct terms but I want to suggest a feature which applies the monocle layout but only to the right area where the leafs are placed. The window on the left would still be visible. It is like the deck patch for dwm (https://dwm.suckless.org/patches/deck/). It should be possible to rotate through the stacked windows.

**Comment by baskerville** [comment] 2019-07-05 07:56
This is a duplicate of #584.

**Closed** 2019-07-05 10:22 UTC
