### ISSUE TITLE
Using --to-node does not preserve orientation

### ISSUE THREAD

**Issue by MartinSandfuchs** [baskerville/bspwm#833] opened 2018-08-25 18:14 UTC
Steps to reproduce:
1. Start with a clean desktop
2. Open 3 windows in automatic mode (windows 1 through 3)
3. Make a preselection on window 2

The layout should look like this (P is the preselection):
```
+-----------------------+
|           |     |     |
|           |  2  |  P  |
|           |     |     |
|     3     |-----------|
|           |           |
|           |     1     |
|           |           |
+-----------------------+
```
When now running `bspc node -n newest.!automatic.local` (with window 3 focused) we expect the following layout:
```
+-----------------------+
|           |           |
|     2     |     3     |
|           |           |
|-----------------------|
|                       |
|           1           |
|                       |
+-----------------------+
```
but instead we get:
```
+-----------------------+
|     |     |           |
|     |     |           |
|     |     |           |
|  2  |  3  |     1     |
|     |     |           |
|     |     |           |
|     |     |           |
+-----------------------+
```

**Comment by baskerville** [comment] 2018-08-25 18:50
This is a duplicate of #832.

**Closed** 2018-08-25 18:51 UTC
