### ISSUE TITLE
Double borders request

### ISSUE THREAD

**Issue by BillyTheMotherBoard** [baskerville/bspwm#877] opened 2018-11-18 17:42 UTC
Hello guys, 
Bspwm is my favorite wm at the moment, I'm totally in love with it, the only thing it needs is double borders, just like in 2bwm.
Please guys add this feature it would be amazing, it's the last thing I need to complete my rice, I used successfully third party scripts to get double borders but there is still a visual retard between the double border drawing and the native bspwm border so it would be amazing to have it as bspwm native feature.

Do you think it can be implemented in the near future?

**Comment by neeasade** [comment] 2018-11-18 18:44
duplicate of https://github.com/baskerville/bspwm/issues/492

**Comment by mcolligan** [comment] 2018-11-24 19:58
@BillyTheMotherBoard This is the base of what I use, it works great for me. You need chwb2 as mentioned in the other issue referenced by neeasade

https://gist.github.com/mcolligan/7581fac56958b633c528b987850ff5ee
(github ruined the formatting)

**Comment by neeasade** [comment] 2018-11-25 00:45
@mcolligan FWIW @BillyTheMotherBoard and I had a related discussion here: https://github.com/neeasade/dotfiles/issues/15

**Comment by jallbrit** [comment] 2020-07-28 18:44
Considering this is a duplicate of #492 like @neeasade said, please close this issue @BillyTheMotherBoard .

**Comment by jallbrit** [comment] 2020-08-10 04:58
@baskerville please close this duplicate.

**Closed** 2020-08-10 08:01 UTC
