### ISSUE TITLE
Severe focus issues since commit 12edac8

### ISSUE THREAD

**Issue by d125q** [baskerville/bspwm#443] opened 2016-04-10 10:52 UTC
I have been having some pretty serious issues since commit [12edac8](https://github.com/baskerville/bspwm/commit/12edac86fa3be32f799bedca4c8f5c0287a735b0).  I have removed all `sxhkd` mouse bindings.

The scenario is the following:

1. Have a monocle desktop;
2. Open a Firefox and a Chromium window on that desktop;
3. Focus the Firefox window and start typing something into the location bar;
4. Focus the Chromium window and try to type something.  You're still typing into Firefox's location bar.

**Comment by kevinvdburgt** [comment] 2016-04-10 12:15
I can confirm, having the same issues, however it seems sometimes complete random for me.

Same thing happens when having multiple terminal open (urxvt).

**Comment by cju** [comment] 2016-04-10 12:49
I can also confirm and I have a experienced a pretty similar issue, which is imho likely to be caused by the same bug, so I allow myself to post it here:

1. Open ranger in a terminal;
2. Navigate to an image an open it with for example feh;
-> the feh node gets focused.
3. Focus the ranger node and try to focus the feh node again; -> the feh node can't be focused anymore.

**Comment by baskerville** [comment] 2016-04-10 16:17
Fixed by 6f0bfe9.

**Closed by baskerville** 2016-04-10 16:17 UTC
