### ISSUE TITLE
Save layout

### ISSUE THREAD

**Issue by eyvindbjartiandersen** [baskerville/bspwm#582] opened 2016-12-02 21:35 UTC
Is there a way to save layouts?. And why not?.

**Comment by alecive** [comment] 2016-12-05 18:35
Duplicate of #371 (which is a duplicate of #259 ) ?

**Comment by baskerville** [comment] 2017-02-02 10:22
Parametric layouts are possible thanks to receptacles.

**Closed by baskerville** 2017-02-02 10:22 UTC

**Comment by baskerville** [comment] 2017-02-04 10:48
Have a look at `examples/receptacles`.

**Comment by eyvindbjartiandersen** [comment] 2018-02-03 10:38
Could you provide a well documented way to use it?.
