### ISSUE TITLE
Anymore thoughts on Wayland?

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [baskerville/bspwm#1068] opened 2020-02-26 12:59 UTC
[Almost 5 years ago](https://github.com/baskerville/bspwm/issues/199#issuecomment-101278791) you said if you were to rewrite bspwm for wayland you would write it in rust. 

I am curious if you have given this anymore thought? I love the rust programming language and am newish to bspwm but I really like it too. Especially as an alternative window manager for KDE plasma. I would help in anyway I could to support a rusty Wayland BSPWM.

**Comment by smhsketch** [comment] 2020-03-25 14:47
+1 on this. I was really excited to find it was in the making, the only thing stopping me from moving to wayland is the lack of bspwm

**Comment by cjk** [comment] 2020-03-28 15:46
Yep, wayland-support + being based on Rust (i.e. fast, secure, stable) + fully customizable tiling-WM would mean a breakthrough for this package. Bspwm could become one of the top WMs out there.

**Comment by maxdeviant** [comment] 2020-04-05 18:48
Let me preface this by saying that I would love to see a port/rewrite of bspwm for Wayland, and I would love it even more if it were written in Rust.

That said, this isn't something that happens overnight. A full rewrite of bspwm is a sizable effort even before taking into account the switch to Wayland. From what I understand, Wayland support in Rust is still very much a work-in-progress.

One of the other Rust-based Wayland WMs mentioned in the other thread, Way Cooler, was [declared dead](http://way-cooler.org/blog/2020/01/09/way-cooler-post-mortem.html) at the beginning of this year. Additionally, the Rust-based Wayland compositor Way Cooler was built on, `wlroots-rs` was also [abandoned](http://way-cooler.org/blog/2019/04/29/rewriting-way-cooler-in-c.html).

Right now the best option appears to be [Smithay](https://github.com/Smithay/smithay), but I cannot speak to its maturity as a library.

I certainly can't speak for @baskerville; I don't know if they will agree with me entirely or not, but I think that biding our time and waiting for Wayland support to mature in Rust will only make things easier for if/when we decide to pursue this.

**Comment by jallbrit** [comment] 2020-08-04 02:36
This issue is a duplicate of #199, just as you mentioned in the issue description. It would be detrimental for further discussion to be fragmented between the 2 issues, and I recommend that you close this issue @Th3Whit3Wolf.

**Closed** 2020-08-04 05:31 UTC
