### ISSUE TITLE
Keep new windows in the desktop it was called.

### ISSUE THREAD

**Issue by ghost** [baskerville/bspwm#760] opened 2018-01-10 20:14 UTC
Hi!

When a new program is started it is opened in the desktop in focus and not in the one it was called.

This behavior isn't a problem when the program open fast, but while opening a program like Gimp, that does take some time to open, one (like me) may like to switch to another desktop to do other tasks and get back later to that opened program. But, when the program finally open in the focused desktop it could mess the layout.

The idea is to modify that behavior to record in what desktop a (random) program where called and make it open in that desktop automatically. I mean, without manually setting in what specific desktop that specific program should always open.

i3 already works in this way, inclusive when the program is started by the terminal.

For the record there was a quick talk today about that in #bspwm with anthony25.

Thank you.
LBdM.

**Comment by baskerville** [comment] 2018-01-11 09:43
This looks like a duplicate of #526.

**Comment by jallbrit** [comment] 2020-08-10 05:13
@baskerville the issue creator has deleted his or her account and this does appear to be a duplicate, please close the issue.

**Closed** 2020-08-10 08:00 UTC
