### ISSUE TITLE
Automatically move node to desktop

### ISSUE THREAD

**Issue by BigfootN** [baskerville/bspwm#968] opened 2019-05-20 13:49 UTC
Hello,

I am trying to add the following rule in my `bspwmrc`:

```
bspc rule -a spotify desktop=music
```

Unfortunately when opening spotify, it opens on the current desktop, not the `music` desktop.

My bspwm version is the following: `0.9.7`.

Thank you very much in advance for any help.

**Comment by mdutra** [comment] 2019-05-20 17:58
The syntax:
```
bspc rule -a (<class_name>|*)[:(<instance_name>|*)] desktop=music
```

I believe spotify's `<class_name>` is "Spotify", not "spotify". You can find out with `xprop | grep WM_CLASS`.

So this will probably fix:

```
bspc rule -a Spotify desktop=music
```

**Comment by BigfootN** [comment] 2019-05-20 18:50
Thank you for your response.

I tried your solution but unfortunately it still doesn't work.

And `xprop | grep WM_CLASS` returns:
```
WM_CLASS(STRING) = "spotify", "Spotify"
```

Thank you again in advance for any help.

**Comment by mdutra** [comment] 2019-05-21 02:34
No problem.

Run this command to see if it prints your desktop name "music" (all lowercase):
```
bspc query -D --names
```

**Comment by BigfootN** [comment] 2019-05-21 09:12
`bspc query -D --names` does return `music` in the list.

Thank you again in advance for any help.

**Comment by mdutra** [comment] 2019-05-21 18:19
It seems to be a problem with Spotify as mentioned here #291.

**Comment by baskerville** [comment] 2019-05-22 07:21
This is, indeed, a duplicate of #291.

**Closed by baskerville** 2019-05-22 07:21 UTC

**Comment by BigfootN** [comment] 2019-05-22 12:33
Thank you for your precious help.
