### ISSUE TITLE
Sticky fullscreen windows

### ISSUE THREAD

**Issue by rr-** [baskerville/bspwm#298] opened 2015-10-24 21:51 UTC
My use case looks like this:

1. Have an empty workspace.
2. Open a fullscreen window, let's call it *A*.
3. Open a floating window, let's call it *B*.
4. *A* goes from fullscreen back to its tiled state.

My problems with 4. are as follows:

1. I see the gaps from the desktop + panel, which is a bit distracting (especially if the contrast is high)
2. It causes *A* to rerender itself, which sometimes causes flicker (especially with ncurses based programs residing inside terminals)
3. If there are other tiled windows, they get rearranged due to layout change, which distracts me even more.

Is there any chance to make *A* stay in fullscreen mode, while having *B* rendered on top of it (like it is when displaying on top of regular tiled windows)?

**Comment by baskerville** [comment] 2015-10-25 13:09
My plan is to provide stacking layers (*below*, *normal* and *above*).

And to let the user decide how she wants to deal with fullscreen windows.

**Comment by baskerville** [comment] 2015-10-26 20:20
It should be fixed by 40cdd64.

**Comment by rr-** [comment] 2015-10-26 21:10
It works almost perfectly, but my panel (written in Qt) is now rendered on top of fullscreen windows. To illustrate this behavior - they overlap each other like this:

    +--------------------+
    | + - - - - - - - - -+-+ overlap, and panel is rendered on top of the window
    +--------------------+ |
      |                    |
      |                    |
      |                    |
      |                    |
      |                    |
      +--------------------+

What *doesn't* happen:

    +--------------------+
    |                    | panel is recognized as a part of screen working area
    +--------------------+-+
      |                    |
      |                    |
      |                    |
      |                    |
      |                    |
      +--------------------+

(sorry for lame ASCII.)

Any tips how can I change panel's z-index? I tried creating window with `Qt.WindowStaysOnBottomHint` to no avail.

**Comment by rr-** [comment] 2015-10-26 21:18
Additionally, having a fullscreen window causes it to be included in tiling layout like this:

    +-fullscreen--------------+
    | +-tiled1--+ +-tiled2--+ |
    | |         | |         | |
    | |         | |         | |
    | |         | +---------+ |
    | |         |             |
    | |         |      !      |
    | |         |             |
    | +---------+             |
    +-------------------------+

**Comment by rr-** [comment] 2015-10-26 22:38
Most of the problems were solved with external scripts. :3

**Comment by baskerville** [comment] 2015-10-27 10:08
As the commit message says fullscreen windows are no longer special.

The issue you're experiencing is linked to the fact that *bspwm* doesn't manage, and in particular doesn't stack unmanaged windows (like panels).

The previous *solution* was to raise the fullscreen windows above every other windows (including unmanaged windows).

If you want to emulate this behavior, the proper way to do it is to read from `bspc control --subscribe window_state` (I'll post a script).

**Comment by rr-** [comment] 2015-10-27 10:46
But won't having fullscreen windows rendered on top of all other windows nullify all of the benefits of the layers - will one be able to still have floating windows render above such fullscreen windows?

Also... what do you think about splitting the `manage` flag into several smaller flags: `manage_stack`, `manage_layout`, `manage_focus` etc.?

**Comment by baskerville** [comment] 2015-10-27 11:23
Right, so lowering the panel (`xdo lower ...`) would be better.

Regarding *manage_stack*: the problem is that there's no such thing as a partially managed window: either it's in one of the trees or it isn't.

**Comment by baskerville** [comment] 2015-10-27 12:35
I'm thinking of adding selectors: `.samelayer` and `.otherlayer` or `.normal`, `.above` and `.below`?

**Comment by Chrysostomus** [comment] 2015-10-27 12:40
Latter seems more intuitive option

**Comment by baskerville** [comment] 2015-10-27 19:32
@rr- in fact the best option is to put the panel below the fullscreen window with `xdo below -t FULLSCREEN_WID PANEL_WID`.

**Comment by baskerville** [comment] 2015-10-27 20:51
@Chrysostomus the new modifiers are available as of 65bc79f.

**Comment by baskerville** [comment] 2015-10-27 21:17
@rr- Here's my script:
```shell
#! /bin/bash

panel_wid=$(xdo id -a panel)

bspc control --subscribe window_state | while read msg name state wid ; do
	[[ $name == "fullscreen" && $state == "on" ]] && xdo below -t $wid $panel_wid
done
```

**Comment by rr-** [comment] 2015-10-27 21:23
@baskerville thanks, I used slightly different approach with wrapper script for fullscreen toggling, but essentially it does the same thing.

Didn't know of `xdo below -t` before I created #299, #299 now seems pointless...

**Closed** 2015-10-28 11:04 UTC
