### ISSUE TITLE
Needing to move into preselected area two times 

### ISSUE THREAD

**Issue by Brett99** [baskerville/bspwm#832] opened 2018-08-23 04:14 UTC
I would like to have a keyboard shortcut that moves the focused window into the preselected area on my desktop. If there is no preselection, it should swap with the largest window. 

Issue #429 explains how to move into a preselected area, but it doesn't work reliably for me. I have to run the command 2 or 3 times to get it to work.

Also, [this](https://github.com/Chrysostomus/bspwm-scripts/blob/master/bin/windowpromoter) script seems to do what I want, but I think it's outdated, because it's not working for me.

**Comment by Brett99** [comment] 2018-08-23 04:32
I'm now using `bspc node -n newest.!automatic.local`, but I sitll need to do it twice. 

Example:


* I have three windows, one big one on the left and two smaller ones stacked on top of each other on the right.  
* I want to turn this into three horizontal windows.
* I preselect the bottom half of the bottom right window 
* I focus on the large window
* I invoke `bspc node -n newest.!automatic.local`
* The large window gets swapped with the bottom right one
* I move them back
* I preselect the bottom right window again
* I focus on the large window
* I invoke `bspc node -n newest.!automatic.local`
* Now it works

**Comment by Brett99** [comment] 2018-08-23 21:40
For some reason the ID of the window changes after the swap. Once it's changed, the command works properly. Why is this?

**Comment by Brett99** [comment] 2018-08-23 22:04
I can try seemingly the same exact thing twice, but it only works on the second time. 

Here is the diff of `bspc query -T -d focused` on the non-working and working one:

```
15c15
<     "id": 12583082,
---
>     "id": 12583081,
40c40
<       "birthRotation": 90,
---
>       "birthRotation": 0,
85c85
<       "id": 12583081,
---
>       "id": 12583084,
110c110
<         "birthRotation": 0,
---
>         "birthRotation": 90,
```

**Comment by Brett99** [comment] 2018-08-23 22:14
If I insert the last window manually, the command works on the first try. If it's inserted automatically, I need run it twice.

**Comment by Brett99** [comment] 2018-08-24 09:01
After some poking around in gdb, I found that setting `ns->birth_rotation = 0;` at the beginning of `transfer_node()` fixes the issue. I don't *think* it broke anything else. 

Is there a correct way to fix this?

**Comment by baskerville** [comment] 2018-08-24 09:57
I can't reproduce: `bspc node -n 'newest.!automatic.local'` works as expected on the first try.

**Comment by baskerville** [comment] 2018-08-24 09:57
> I get bash: !automatic.local: event not found

`!` is a special shell character and needs to be escaped.

**Comment by baskerville** [comment] 2018-08-24 12:13
Thanks, I was able to reproduce and I will investigate.

**Comment by baskerville** [comment] 2018-08-24 15:53
If you spawn a few windows on an empty desktop, you'll notice that each time a window is added the existing tree rotates in clockwise direction (I'm assuming that `initial_polarity` is `first_child`). If you remove the *n*-th window, the tree rooted at its brother will rotate in counterclockwise direction in order to put the tree back into the state it was in before the insertion of the *n*-th window. That's how the automatic insertion mode works since the dawn of *bspwm* and that's why nodes need to remember their *birth rotation*.

What happens in our case is that `-n` uses the same function as `-d` and `-m`: `transfer_node`. This function is mainly calling two other primitives: `unlink_node` and `insert_node`. And since the node we're unlinking was inserted in automatic mode, its brother is rotated in counterclockwise direction. Hence the unexpected result.

One way of solving this problem would be to reset the birth rotation when we're transferring a node to its current desktop (that is, when `ds == dd`).

Or maybe I should introduce a setting to prevent the brother tree from being rotated when a node is unlinked?

**Closed** 2018-08-25 18:54 UTC
