### ISSUE TITLE
Cycle focusing bug that focuses multiple windows at once

### ISSUE THREAD

**Issue by feroldi** [baskerville/bspwm#1187] opened 2020-09-02 03:36 UTC
I'm currently facing an annoying bug with `bspc node -f {next,prev}.local`.

Say I have four windows open in a workspace: A, B, C, and D. And that the window A is the one focused. When `bspc node -f next.local` is run, all windows get focused at once. Another run, then B gets focused. Another run, then B, C, and D gets focused at once.

I'm in 0.9.10, and I don't use anything other than bspwm for window management, and sxhkd for key mappings.

**Comment by emanuele6** [comment] 2020-09-02 03:44
That is not a but, `bspc node -f next.local` should behave like that in `bspwm 0.9.10`.

Read the changelog for more information or read how to write a command which emulates the old behaviour in one of the duplicate issues.

This issue is a duplicate of #1168, #1171, #1172, #1177, #1182 and #1184 (this is issue #1187).

**Comment by feroldi** [comment] 2020-09-02 04:47
Thanks, that makes sense.

By the way, this seems like a breaking change. Shouldn't the version have been bumped to 0.10.0 at least?

**Comment by emanuele6** [comment] 2020-09-02 04:49
> Shouldn't the version have been bumped to 0.10.0 at least?

I expected the same honestly.

**Closed** 2020-09-02 05:07 UTC
