### ISSUE TITLE
Trying to move spotify to desktop 8, what I'm I doing wrong?

### ISSUE THREAD

**Issue by gregf** [baskerville/bspwm#1011] opened 2019-09-12 22:01 UTC
```
❯ bspc rule -a spotify desktop="^8"

~
❯ bspc rule -a spotify desktop='^8'

~
❯ bspc rule -a Spotify desktop='^8'

~
❯ man bspc

~ took 22s
❯ bspc rule -a :Spotify desktop='^8'

~
❯ bspc rule -a :spotify desktop='^8'

~
❯ xprop
_NET_WM_ICON(CARDINAL) =
WM_CLASS(STRING) = "spotify", "Spotify"
WM_NAME(STRING) = "Spotify Premium"
_NET_WM_NAME(UTF8_STRING) = "Spotify Premium"
_NET_WM_DESKTOP(CARDINAL) = 5
WM_STATE(WM_STATE):
                window state: Normal
                icon window: 0x0
XdndProxy(WINDOW): window id # 0x2a00002
WM_NORMAL_HINTS(WM_SIZE_HINTS):
                program specified location: 0, 0
                window gravity: Static
_NET_WM_PID(CARDINAL) = 11083
WM_LOCALE_NAME(STRING) = "en_US.UTF-8"
WM_CLIENT_MACHINE(STRING) = "fluffy.local"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, _NET_WM_PING

~ took 2s
❯ bspc rule -a "Spotify" desktop='^8'

~
❯ bspc rule -a "Spotify Premium" desktop='^8'

~
❯ bspc rule -a Spotify Premium desktop='^8'
```

**Comment by dotnetfox** [comment] 2019-09-13 07:32
According to ``man bspwm`` you have to move the node with the ``bspc node -d ^8`` command.
Your current actions won't move the node to another desktop.

**Comment by baskerville** [comment] 2019-09-13 09:32
This is a duplicate of #291.

**Closed by baskerville** 2019-09-13 09:32 UTC
