### ISSUE TITLE
Query modifier quirks

### ISSUE THREAD

**Issue by eigengrau** [baskerville/bspwm#249] opened 2015-05-12 08:46 UTC
When using the current head, query modifiers don’t seem to work as expected.

E. g., when desktop `I` is free, `bspc query -D -d I.free` and `bspc query -D -d I.occupied` both yield `I`.

Generally, the individual queries for `newer.occupied`, `newer.free`, `older.occupied`, `older.free` should yield the list of all desktops. However, the modifier sometimes seems to only yield a single match, even when the selector should match multiple desktops.

**Comment by eigengrau** [comment] 2015-05-12 08:50
Relatedly, `bspc query -D -d left` only lists a single desktop, even when there are multiple desktops in the cycle direction.

**Comment by baskerville** [comment] 2015-11-25 13:04
The first *quirk* (in fact the syntax was invalid at the time) is fixed by 512e904.

**Comment by Stebalien** [comment] 2015-11-25 15:52
> Relatedly, bspc query -D -d left only lists a single desktop, even when there are multiple desktops in the cycle direction.

I assume you mean `prev`; `left` is an invalid selector for desktops. Regardless, this is the intended behavior. `bspc query -D -d prev` means "what is the previous desktop".

**Closed** 2016-03-26 17:22 UTC
Labels: enhancement

**Comment by eigengrau** [comment] 2016-03-26 17:28
Ah, sorry, somehow lost track of this. I suppose I confused the selector syntax back when I filed this. Thanks for the selector modifier enhancements though!
