### ISSUE TITLE
closed windows are visible for xfce4-panel / probably other panels

### ISSUE THREAD

**Issue by Limdel** [baskerville/bspwm#388] opened 2016-02-03 13:13 UTC
Hello. I'm using xfce4-panel, and after last update it doesn't recognize windows closing correctly or something like that. after I close last window on workspace and focus is empty I still can see it in my taskbar and pager till I focus other existing window.

attaching screenshots:
![zflvc9i](https://cloud.githubusercontent.com/assets/17046062/12783172/f2fe155c-ca90-11e5-9344-15af996d0aba.png)
![cemffzn](https://cloud.githubusercontent.com/assets/17046062/12783171/f2f4e9be-ca90-11e5-86be-52946362694d.png)

EDIT: Same behavior confirmed for mate-panel too.

**Comment by Limdel** [comment] 2016-02-04 11:15
I found a workaround for the panel bug. I figured out that it glitches only when there is nothing to focus, so I thought if it would be able to focus panel, it will work properly. so I added a simple rule and everything works like before now.
`bspc rule -a Xfce4-panel manage=true border=false locked=true`

**Comment by Limdel** [comment] 2016-02-04 11:40
I found a workaround for the panel bug. I figured out that it glitches only when there is nothing to focus, so I thought if it would be able to focus panel, it will work properly, so I added a simple rule and everything works like before now.
`bspc rule -a Xfce4-panel -o manage=true border=false`

**Comment by Limdel** [comment] 2016-02-17 16:38
some update.
to make whisker menu work with it too, the proper rules would be:
`bspc rule -a Xfce4-panel manage=true border=off
bspc rule -a Wrapper-1.0 center=false border=off`

**Comment by aminb** [comment] 2016-02-26 16:40
Same issue here.

@Limdel's workaround only *kinda* works:

1. It makes the panel flicker when switching desktops (workspaces)
2. Each time I close a window, the panel is given focus instead of the next window on the desktop, which is very annoying.

So, a proper fix for this would be much appreciated.

Given that I don't have this problem with bspwm 0.9, I'm curious to know what's causing this on master.

@Limdel have you managed to pin point the cause of the issue?

**Comment by baskerville** [comment] 2016-02-26 17:20
The output of `xev -root` *might* be helpful.

I'm not familiar with *xfce4-panel*: how can I reproduce the problem?

**Comment by aminb** [comment] 2016-02-26 19:34
How to reproduce:

1. open any window on some workspace
2. open another window on some other workspace
3. go back to the workspace containing the first window
4. close the window

Observe that on master, the application icon is still displayed on the xfce panel despite the fact that it was closed (look at @Limdel's second screenshot). This doesn't happen with bspwm 0.9, meaning that when closing an application, its icon disappears from the xfce panel workspace preview (as it should).

I've made two observations:

1. This problem with bspwm master only happens when there's more than one window open (across all workspaces). So, if there's only one window open, when I close it its icon disappears from xfce panel right away.
2. When the problem does happen (when two or more windows are open, and you close one of them and its icons remains), the icon goes away when switching to any workspace that has a window in it.
So, in the scenario I describe below, the stuck icon disappears when I switch to workspace 3.

---

Output of `xev -root` as requested:

- using bspwm master
[xev-0.9-git.txt](https://github.com/baskerville/bspwm/files/148773/xev-0.9-git.txt)
- using bspwm 0.9
[xev-0.9.txt](https://github.com/baskerville/bspwm/files/148774/xev-0.9.txt)

What I did to generate the logs:

1. open two urxvt terminals, one on workspace 1, the other on workspace 3
2. in the terminal on workspace 3 run `xev -root > xev-0.9-git.txt`
3. switch to workspace on using <kbd>Super + 1</kbd>
4. close the terminal using <kbd>Super + w</kbd>
5. go back to workspace 3 and do <kbd>Control + c</kbd>

I repeated the same thing to for generating `xev-0.9.txt` on bspwm 0.9.

**Comment by baskerville** [comment] 2016-02-26 21:22
Thanks.

It should be fixed as of 4b538bc.

**Comment by aminb** [comment] 2016-02-26 22:15
Awesome, can confirm it's fixed for me.

Thanks @baskerville!

**Closed** 2016-02-27 09:37 UTC
