### ISSUE TITLE
Is it possible to create a startup workspace?

### ISSUE THREAD

**Issue by CvRXX** [baskerville/bspwm#371] opened 2016-01-11 22:51 UTC
Hello,

I was wondering if it was possible to launch some applications at startup and define where they will spawn. So that you get the same layout every time you boot.

Hope this is possbile!

Thanks in advance.

**Comment by baskerville** [comment] 2016-01-12 09:03
Not yet.

This is a duplicate of #259.

**Comment by ploz** [comment] 2016-01-13 09:19
It is!
Though it *may* be possible to use exported world states and JSON trees, a simple script with one-shot rules will suffice.
```bash
#!/bin/sh
bspc desktop -f ^1
urxvtc &
sleep 0.05

#bash session persists after lynx closes
bspc rule -a URxvt -o split_dir="east" split_ratio="0.5" && urxvtc -g 53x8 -e /bin/bash -c "lynx && /bin/bash" &
sleep 0.05

bspc rule -a URxvt -o split_dir="north" split_ratio="0.489" locked=on  && urxvtc -e toxic &
sleep 0.05

bspc node -f west
bspc rule -a URxvt -o split_dir="south" split_ratio="0.858" state=pseudo_tiled && urxvtc -g 53x8 -e tty-clock -bscC3 &
sleep 0.05

#bspc desktop -f ^2
bspc rule -a Firefox -o desktop=^2 state=floating && firefox &
```
There are a few drawbacks to this method
* if you are trying to create a specific tiling tree, that desktop will more than likely need to be active
* sleep commands are required; delay value may need to vary
* a sleep system can screw with application placement if it's the application's first start
	* not sure how to get around this. Higher sleep values or using your init system to exec script when bspwm starts may help.
	* running the script a loop that checks how many windows are open might work as an alternative to sleep

You may also need to customize `split_ratio` to account for your particular resolution, window gap, border width, and padding.

**Comment by baskerville** [comment] 2016-03-26 17:19
Fixed by e8aa679.

**Closed by baskerville** 2016-03-26 17:19 UTC

**Comment by CvRXX** [comment] 2016-09-08 13:37
could you explain how this actually makes startup workspaces possible?

**Comment by baskerville** [comment] 2016-09-08 17:04
An example is given in the commit message.

**Comment by alecive** [comment] 2016-10-11 22:45
@baskerville can you explain a bit the commit message? I'm sorry but I don't think I understood it completely.

**Comment by mrkgnao** [comment] 2016-12-05 18:05
I agree, some explanation would be nice.

**Comment by mikeyjk** [comment] 2017-05-05 02:38
Apologies for being a noob, but how do I attach a new process to one of these receptacles?

**Comment by baskerville** [comment] 2017-05-05 07:33
See `examples/receptacles`.
