### ISSUE TITLE
Rule to stick on a program in whatever workspace?

### ISSUE THREAD

**Issue by edn9** [baskerville/bspwm#980] opened 2019-06-11 13:49 UTC
Its possible to make a rule that everytime I open a new program, they sticky in the workspace that I open it?
Example: If I open Steam in workspace 7, the Steam will stick in that workspace, whatever workspace I am after doing that command.

I dont like using rules that strict programs to only open in x y z workspace, I like to use it freely, so I hope to see a way to do that. When I open a program they dont sticky in that workspace that I used the command to open, they open in whatever workspace I am and sometimes I need to wait for the program to open to finally move to another workspace and to other stuff.
I'm sorry for my english and the duplicate question (if already asked before).

**Comment by baskerville** [comment] 2019-06-11 16:18
This looks like a duplicate of #190 and #526.

**Closed** 2019-07-19 07:54 UTC
