### ISSUE TITLE
node focus gets all windows

### ISSUE THREAD

**Issue by derrickcope** [baskerville/bspwm#1171] opened 2020-08-08 09:48 UTC
I have this in my sxhdkrc to toggle focus on windows on the same desktop. Since the new update It still does toggle focus but at one point all windows will be focused at one time.

alt + {Tab,Escape}
     bspc node -f {next,prev}.local

not sure if I am doing something wrong or not

**Comment by derrickcope** [comment] 2020-08-08 10:30
I seemed to have solved the problem by adding .window
I'm not sure why my original was getting all windows at one point.

**Comment by emanuele6** [comment] 2020-08-08 14:11
duplicate of #1168.

> not sure if I am doing something wrong or not

You are: since `bspwm 0.9.10`, *CYCLE_DIR* descriptors (`prev` and `next`) can select any kind of nodes, not just non-hidden leaf nodes which contain a window. As you already figured out, you can use `prev.local.window` and `next.local.window` to only select leaf nodes which contain a window. (note that `.!hidden` is not necessary because `node -f` skips hidden nodes.)

-----------------------
`man 1 bspwm`
```
CYCLE_DIR
    Selects the node in the given (cyclic) direction relative to
    the reference node within a depth-first in-order traversal of
    the tree.
```

**Closed** 2020-08-08 16:44 UTC
