### ISSUE TITLE
Can't focus windows by direction after reload

### ISSUE THREAD

**Issue by mbennehar** [baskerville/bspwm#217] opened 2015-02-25 18:03 UTC
Hello there, I'm using bspwm with the loop example so what I've done is that I placed wm in a directory included in path, made the modifications to bspwmrc and sxhkdrc and .zprofile and everything is working as it should be. One issue though is when I use ctrl+super+escape command I can't focus windows by directions. pressing super + i,j,k,l doesn't seem to work.

**Comment by NicolasCARPi** [comment] 2015-06-02 16:15
I can't reproduce this bug. Can you try with latest git version ?

**Comment by baskerville** [comment] 2015-11-13 18:00
Fixed by 6fb0469.

**Closed by baskerville** 2015-11-13 18:00 UTC
