### ISSUE TITLE
Transparent borders! [Feature Request]

### ISSUE THREAD

**Issue by linyostorovovoltos** [baskerville/bspwm#670] opened 2017-07-02 22:26 UTC
The one thing that really bothers me is that there is no option for transparent borders! The title says it all! I'm not sure if this needs to be achieved with compton or a compositor, but, if you can, please see if you can get this to work! Thank you for spending your time reading this!

**Comment by baskerville** [comment] 2017-07-03 06:44
This is a duplicate of #236.

**Closed by baskerville** 2017-07-03 06:44 UTC
