### ISSUE TITLE
Preselect color on borders ONLY?

### ISSUE THREAD

**Issue by D3faIt** [baskerville/bspwm#891] opened 2018-12-12 15:02 UTC
Hi.

I was wondering if it is possible to only showing preselect color on the borders instead of having a huge fucking box showing up.

I edited a screenshot in photoshop, and basically want this kind of preselect style:

![presel_color](https://user-images.githubusercontent.com/8147434/49862945-88e50b80-fdff-11e8-8e17-718958efa3c8.png)

Are there any methods to achieve this?

**Comment by baskerville** [comment] 2018-12-12 16:57
Duplicate of #861.

**Closed by baskerville** 2018-12-12 16:57 UTC

**Comment by D3faIt** [comment] 2018-12-12 19:23
@baskerville Do you have any documentation on this?

This is my current configuration:
# .bspwmrc
```
#! /bin/sh

sxhkd &

bspc monitor -d 一 二 三 四 五 六 七 八 九 十

bspc config border_width         5
bspc config window_gap          24

bspc config split_ratio         0.56
bspc config bottom_padding      0
bspc config borderless_monocle  true
bspc config gapless_monocle     true

bspc config normal_border_color   \#101317
bspc config focused_border_color  \#76628A
bspc config presel_feedback_color \#C57E87
```

# .sxhkdrc (only preselect)
```
super + {h,v}
         bspc node -p {east,south}
```
